Initialize an empty array with size 2X2.

In [9]:
import numpy as np

a = np.empty((2,2))
print(a)

[[2.12199579e-314 1.12677977e-311]
 [5.35567160e-321 1.12677977e-311]]


Initialize an all one array with size 4X2.

In [11]:
import numpy as np
b = np.ones((4,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [12]:
import numpy as np
new_arr = np.full((4,2),4)
print(new_arr)

[[4 4]
 [4 4]
 [4 4]
 [4 4]]


Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [14]:
import numpy as np
new_array = np.zeros_like(new_arr)
print(new_array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [15]:
import numpy as np
new_array_of_one = np.ones_like(new_array)
print(new_array_of_one)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [16]:
import numpy as np
new_list = [1,2,3,4]
a = np.array(new_list)
print(a)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [17]:
import numpy as np
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [18]:
import numpy as np
a = np.arange(9)
a = np.reshape(a,(3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3X3 identity matrix.{Hint:np.eye()}

In [19]:
import numpy as np
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [22]:
import numpy as np
a = np.random.random(30)
print(a)
result = a.mean()
print("mean: ",result)


[0.00552726 0.2205982  0.45811671 0.82325278 0.39371279 0.84213463
 0.01891866 0.77604621 0.46347793 0.657057   0.01363497 0.56088948
 0.97918285 0.21337238 0.50253003 0.81586327 0.33541926 0.54406631
 0.52548036 0.09384127 0.27718187 0.55795646 0.99179689 0.01566838
 0.84397601 0.78412088 0.89137323 0.33082842 0.83135995 0.10253107]
mean:  0.49566385135339647


Create a 10X10 array with random values and find the minimum and maximum values.

In [23]:
import numpy as np
a = np.random.random(100)
reshape_a = np.reshape(a,(10,10))
print(reshape_a)
print("maximum: ",reshape_a.max())
print("minimum: ",reshape_a.min())

[[0.08981004 0.49113002 0.24213224 0.98348371 0.43391147 0.83655331
  0.52883208 0.73198182 0.55861886 0.75052416]
 [0.04931546 0.99586468 0.753413   0.64244444 0.28705516 0.51011313
  0.44933506 0.76818765 0.50552666 0.29153681]
 [0.92673602 0.47885021 0.35516945 0.2001012  0.61716747 0.83468194
  0.61377666 0.78523417 0.68093252 0.88991496]
 [0.00718152 0.31041833 0.12757374 0.62248071 0.48331234 0.14718105
  0.88356625 0.1879485  0.00295473 0.43717718]
 [0.62470861 0.11413358 0.75935951 0.54617943 0.20050192 0.34113162
  0.13146509 0.63191255 0.53642966 0.15672386]
 [0.87331134 0.59788818 0.26660132 0.59927059 0.51629793 0.643333
  0.65090152 0.43807121 0.33866974 0.5417828 ]
 [0.08465693 0.16736322 0.53392568 0.29259286 0.5642804  0.72743091
  0.09779661 0.04588376 0.0901622  0.42951901]
 [0.31871173 0.82164767 0.17040004 0.48908678 0.29846318 0.51554537
  0.82631146 0.18891137 0.7113496  0.13467814]
 [0.29211252 0.45969564 0.65722652 0.29261729 0.68084373 0.75993445
  0.85814461 0

Create a zero array of size 10 and replace 5th element with 1.

In [24]:
import numpy as np
a = np.zeros(10)
np.put(a,4,1)
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Reverse an array arr = [1,2,0,0,4,0].

In [25]:
import numpy as np
arr = [1,2,0,0,4,0]
a = np.flip(arr)
print(a)

[0 4 0 0 2 1]


Create a 2d array with 1 on border and 0 inside.

In [26]:
import numpy as np
a = np.ones(16)
b = np.reshape(a,(4,4))
b[1:-1,1:-1] = 0
print(b)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Create a 8X8 matrix and fill it with a checkerboard pattern.

In [27]:
import numpy as np
a = np.zeros((8,8))
a[1::2,0::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

For the following arrays:<br>
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]); <br>
v = np.array([9,10]) and w = np.array([11,12]); <br>
Complete all the task using numpy:

In [35]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# Add the two array.
print("add x+y: ",np.add(x,y))

# Subtract the two array.
print("subtract w-v: ",np.subtract(w,v))

# Multiply the array with any integers of your choice.
print("multiply x*4: ",np.multiply(x,4))

# Find the square of each element of the array.
print("square of x: ",np.power(x,2))

# Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print(f"the dot product of v and w is {np.dot(v,w)}")
print(f"the dot product of x and v is {np.dot(x,v)}")
print(f"the dot product of x and y is {np.dot(x,y)}")

# Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
a = np.concatenate((x,y)) 
b = np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))
print(f"Concatenate of x and y along row is {a}")
print(f"Concatenate of v and w along column is {b}")

# Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
# Answer
# if we concatenate x and v we get error because x is 2D array and v is 1D array to concatenate array dimensions must be same.
c = np.concatenate((x,v))


add x+y:  [[ 6  8]
 [10 13]]
subtract w-v:  [2 2]
multiply x*4:  [[ 4  8]
 [12 20]]
square of x:  [[ 1  4]
 [ 9 25]]
the dot product of v and w is 219
the dot product of x and v is [29 77]
the dot product of x and y is [[19 22]
 [50 58]]
Concatenate of x and y along row is [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate of v and w along column is [[ 9 11]
 [10 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:

For the following arrays:<br>
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);<br>
Prove following with Numpy:

In [7]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#Prove A.A−1 = I.
det_A = np.linalg.det(A)
if det_A == 0:
    print("not invertible")
else:
    inv_A = np.linalg.inv(A)
    result = np.dot(A,inv_A)
    I = np.eye(A.shape[0])
    is_identity = np.allclose(result, I)
    
    print(f"Is A * A^-1 equal to the identity matrix? \n {is_identity}")

# Prove AB not equal to BA.
print()
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB = ",AB)
print("BA = ",BA)

print(f"is AB = BA ? \n {np.array_equal(AB,BA)}")

# Prove (AB)T = BTAT
print()
AB_transpose = np.transpose(np.dot(A,B))
A_transpose = np.transpose(A)
B_transpose = np.transpose(B)
B_and_A_transpose = np.dot(B_transpose,A_transpose)

print(f"AB transpose = {AB_transpose}")
print(f"B and A transpose = {B_and_A_transpose}")
print(f"is (AB)^T = B^TA^T ? {np.array_equal(AB_transpose,B_and_A_transpose)}")

Is A * A^-1 equal to the identity matrix? 
 True

AB =  [[23 13]
 [51 29]]
BA =  [[36 44]
 [13 16]]
is AB = BA ? 
 False

AB transpose = [[23 51]
 [13 29]]
B and A transpose = [[23 51]
 [13 29]]
is (AB)^T = B^TA^T ? True


Solve the following system of Linear equation using Inverse Methods.<br>

2x − 3y + z = −1<br>
x − y + 2z = −3<br>
3x + y − z = 9<br>

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}<br>
Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [74]:
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
A_det = np.linalg.det(A)

if A_det == 0:
    print("cannot be slove")
else:
    A_inv = np.linalg.inv(A)
    result = np.dot(A_inv,B)
    print(f"(x,y,z) = {result}")

(x,y,z) = [ 2.  1. -2.]
